version: '3'
services:
  node0:
    image: ghcr.io/casbin/casbin-mesh:latest
    command: >
      --node-id node0
      --enable-basic
      --raft-address 0.0.0.0:4002
      --raft-advertise-address node0:4002
      --endpoint-no-verify
    ports:
      - "4002:4002"
    volumes:
      - ./store/casbin/node1:/casmesh/data
  node1:
    image: ghcr.io/casbin/casbin-mesh:latest
    command: >
      --node-id node1
      --enable-basic
      --raft-address 0.0.0.0:4002
      --raft-advertise-address node1:4002
      --join http://node0:4002
      --endpoint-no-verify
    ports:
      - "4004:4002"
    volumes:
      - ./store/casbin/node2:/casmesh/data
    depends_on:
      - node0
  node2:
    image: ghcr.io/casbin/casbin-mesh:latest
    command: >
      --node-id node2
      --enable-basic
      --raft-address 0.0.0.0:4002
      --raft-advertise-address node2:4002
      --join http://node0:4002
      --endpoint-no-verify
    ports:
      - "4006:4002"
    volumes:
      - ./store/casbin/node3:/casmesh/data
    depends_on:
      - node0